python3-spdx-python-model: fix do_compile error for update of python3-shacl2code
Add patch 0001-Update-gen-generate-bindings-to-output-to-directory-.patch to fix bug when updated python3-shacl2code:

ERROR: python3-spdx-python-model-0.0.4-r0 do_compile: Execution of '/tmp/work/cortexa57-poky-linux/python3-spdx-python-model/0.0.4/temp/run.do_compile.2283925' failed with exit code 1
ERROR: Logfile of failure stored in: /tmp/work/cortexa57-poky-linux/python3-spdx-python-model/0.0.4/temp/log.do_compile.2283925
Log data follows:
| DEBUG: Executing shell function do_compile
| * Getting build dependencies for wheel...
|
| ERROR Missing dependencies:
|       shacl2code==0.0.24
| WARNING: exit code 1 from a shell command.

Signed-off-by: Wang Mingyu <wangmy@fujitsu.com>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>